
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  #namespace: dev
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: backend
          image: ncameiri/iot-basic-backend:app3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app3-svc
  #namespace: kube-system  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app3


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: test-n-ingress-service
#   #namespace: dev
# spec:
#   selector:
#     app: test-n-ingress
#   ports:
#     - protocol: TCP
#       port: 8888
#       targetPort: 80
#   type: LoadBalancer

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3-ing
  #namespace: kube-system
  annotations:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
spec:
  rules:
  - host : app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app3-svc
            port:
              number: 80
