apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-n-ingress
  #namespace: dev
  labels:
    app: test-n-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-n-ingress
  template:
    metadata:
      labels:
        app: test-n-ingress
    spec:
      containers:
        - name: backend
          image: daniginga/iot-basic-backend:app2
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test-n-ingress-service
  #namespace: dev
spec:
  selector:
    app: test-n-ingress
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 3000
  type: LoadBalancer