apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-control
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: app-control
    repoURL: https://github.com/ncameiri/argocd_sync.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true