
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd1
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app1
    repoURL: https://github.com/ncameiri/argocd_sync.git
    targetRevision: HEAD
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd2
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app2
    repoURL: https://github.com/ncameiri/argocd_sync.git
    targetRevision: HEAD


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd3
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app3
    repoURL: https://github.com/ncameiri/argocd_sync.git
    targetRevision: HEAD

---